### ISSUE TITLE
Rocket Launcher values wrong

### ISSUE THREAD

**Issue by JeffyNarwhal** [carlssonemil/nebula#10]
Military camos for rocket launchers should go
- 2
- 5
- 10
- 15
- 20
- 25
- 30
- 40
- 50

Also the **Policia** challenge on the  **CIGMA 2B** should be 10 direct hit kills, not 15

**Comment by JeffyNarwhal** [comment]
#11

**Comment by carlssonemil** [comment]
Fixed in #11.
