### ISSUE TITLE
[Bug] Favorite toggle not working on multiplayer camos

### ISSUE THREAD

**Issue by NowakNick** [carlssonemil/nebula#13]
## Expected behaviour
Clicking the favourite toggle (star) on multiplayer camos will toggle the favourite status.

## Current behaviour
Clicking the toggle on multiplayer camos does nothing. Therefore it is not possible to select a favourite.
The browser console will show the following output when the button is clicked once:

![image](https://github.com/user-attachments/assets/3a3722c7-1b1f-413d-b8a9-83338e6e8b2d)

## Possible solution
Looking at the errors above, it seems that the index is undefined. Either the element doesn't have an index assigned, or it can't be found within an element (e.g. the store).

## Steps to reproduce
1. Open the Came Tracker
2. Click on any bookmark

## Context (Environment)
- The issue only occurs with multiplayer camos. Zombie and warzone cams work fine.
- The issue is browser independent. It has been tested in Chrome, Edge and Safari.

**Comment by carlssonemil** [comment]
Fixed in #20.
