### ISSUE TITLE
[Bug] Hiss Camo missing information

### ISSUE THREAD

**Issue by Noriaela** [carlssonemil/nebula#18]
![firefox_2X2Ea7DOYa](https://github.com/user-attachments/assets/3fdddc7b-3fe3-4a82-8a63-77df4206f240)
![cod_A9ly35cwLd](https://github.com/user-attachments/assets/3a755dda-138a-4edb-88b6-7fef9288acc8)

**Comment by The-Eye-of-Ar3s** [comment]
Working on a pull request

**Comment by carlssonemil** [comment]
Fixed in #19.
