### ISSUE TITLE
[Bug] SWAT 556 Incorrect Zombie Camos

### ISSUE THREAD

**Issue by The-Eye-of-Ar3s** [carlssonemil/nebula#2]
## Current Order

1. 50 Critical Kills
2. 100 Critical Kills
3. 150 Critical Kills
4. 200 Critical Kills
5. 300 Critical Kills
6. 400 Critical Kills
7. 500 Critical Kills
8. 750 Critical Kills
9. 1000 Critical Kills

## Correct Order

1. 100 Critical Kills
2. 200 Critical Kills
3. 300 Critical Kills
4. 400 Critical Kills
5. 600 Critical Kills
6. 800 Critical Kills
7. 1000 Critical Kills
8. 1500 Critical Kills
9. 2000 Critical Kills

**Comment by The-Eye-of-Ar3s** [comment]
Hey if it's helpful at all to you @carlssonemil
https://dotesports.com/call-of-duty/news/black-ops-6-zombies-camo-challenges-list
claims that ALL military camos are of that schema

**Comment by carlssonemil** [comment]
@The-Eye-of-Ar3s that's a great source to complete the camouflage requirements! I'll go through it tomorrow and add everything in! Thanks! 🌟

**Comment by The-Eye-of-Ar3s** [comment]
Another small note:
For weapons where critical kills aren't possible, namely launchers and melee, the critical kills are just regular kills. Amount stays the same, though.
