### ISSUE TITLE
Progression should not only count nebula.

### ISSUE THREAD

**Issue by The-Eye-of-Ar3s** [carlssonemil/nebula#22]
![image](https://github.com/user-attachments/assets/2d7357bf-4c48-4306-b939-f58b58428c40)

This is not a good way to count weapon progression.
By the time the player can make their first progress point, they will already have completed 93% of all camos.

I personally believe gold is best suited to be the standard to mark a single weapon as _"completed"_.

**Comment by carlssonemil** [comment]
I totally get your point. On the one hand it is as you say not really a good progression count when you've almost finished the grind before earning your first completion point. However, technically, you're not completed with the weapon until you've unlocked all the camouflages for it.

I fear that if we change it so it counts as "completed" at a previous stage than *Dark Matter*/*Nebula*/*Abyss*, someone will report it as a bug.

Would adding an option to the settings page suffice? E.g. "*Count weapon as completed when this camouflage has been unlocked*" with a select/dropdown for Gold, Diamond, Dark Spine, Dark Matter, etc?

**Comment by The-Eye-of-Ar3s** [comment]
A dropdown is a great idea, probably better than just counting gold.
It would allow for smoother progression tracking than just a single count could.

**Comment by The-Eye-of-Ar3s** [comment]
That seems perfect to me
Really appreciate all the work you put into this project 🎉
