### ISSUE TITLE
[Bug] Progression Issue with New Weapons

### ISSUE THREAD

**Issue by Glydal** [carlssonemil/nebula#53]
The Saug and the Sirin 9mm progression is messed up.

1.) The 2 Special Camos on each can be marked freely of the Military Camos and will not be automatically unmarked if all Military Camos are not completed.

2.) The 2 Special Camos will automatically mark themselves if any Military Camo is marked completed. This means that when 100 critical kills is marked, both Special Camos will be marked.

3.) Unmarking the first Special Camo unmarks the second and marking the second Special Camo automatically marks the first.

**Comment by Voigtus** [comment]
@Glydal You are referring to the Zombies camos, right?

@carlssonemil seems like the camouflageOrder.js is messed up again. Maybe this could be integrated in a premerge check pipeline (if you are using github-actions). That all camos are present in the camouflageOrder.js

**Comment by Glydal** [comment]
Yeah, the Zombies Camos.

**Comment by Glydal** [comment]
I see the issue has been fixed. Thank you!
