### ISSUE TITLE
Military camos in zombies are mislabeled

### ISSUE THREAD

**Issue by The-Eye-of-Ar3s** [carlssonemil/nebula#6]
Currently, zombies camos are presumed to be the same as in multiplayer.
The actual camos are as following (in slug-case):

slate
desert
evergreen
rugged
grim
stripe
oceanic
whiteout
purple-tiger

followed by two per-weapon special camos followed by

mystic-gold
opal
afterlife
nebula

I do not know you want to handle this change in your codebase, hence why I am opening an issue, not a pull request.

**Comment by carlssonemil** [comment]
I'll have to change the data structure around a bit then! Shouldn't be too hard! 😁
